### ISSUE TITLE
Fix Executor 404 error when getting linearised DataFlow

### ISSUE THREAD

**Issue by riesentoaster** [Agile-Waterfall/flooq#125]
## Error message
<img width="731" alt="image" src="https://user-images.githubusercontent.com/27142200/166915567-b8e4059c-dcff-45ca-87b6-8d86bb438391.png">

This happens on execution of the flow (http://localhost:3500/flow/c78c836a-e85f-4127-91a4-d6d5ecc0de62?a=3 to be precise).

**Comment by riesentoaster** [comment]
<img width="735" alt="image" src="https://user-images.githubusercontent.com/27142200/166917840-3c7dcff3-fefb-4422-a990-f0672e2eb1aa.png">
2 Requests:
- first is for an inexistent flow
- second for an existant

**Comment by S4nvers** [comment]
<img width="1254" alt="Screenshot 2022-05-05 at 15 17 28" src="https://user-images.githubusercontent.com/8488489/166931257-a32e53e2-5762-4614-a02a-f6a6dd205cf6.png">

Axios error reported by @riesentoaster is fixed now but there is still a problem when trying to save a linearized dataflow
