### ISSUE TITLE
WE NEED KAZOOS

### ISSUE THREAD

**Issue by riesentoaster** [Agile-Waterfall/flooq#3]

**Comment by Geissemanu** [comment]
BEHOLD:  the scrum master

**Comment by silvan-flum** [comment]
[![mqdefault_6s](https://user-images.githubusercontent.com/54156690/157029310-9a949b50-f9ae-4f00-85f2-b890cb356717.jpg)](https://www.youtube.com/watch?v=oau9gtG5Om8&ab_channel=JoePenna%2FMysteryGuitarMan)

**Comment by Geissemanu** [comment]
https://www.alibaba.com/product-detail/Kazoo-Kazoo-Kazoo-Musical-Instrument-Metal_60016784986.html?spm=a2700.galleryofferlist.normal_offer.d_title.c04668e7qpaNBh&s=p
